web:
  build: ./web
  volumes:
    - ./web/log:/var/log/nginx
    - ./web/sites-enabled:/etc/nginx/sites-enabled
    - ./web/html:/usr/share/nginx/html
    - ./web/snippets:/etc/nginx/snippets
    - ./web/ca:/etc/nginx/ca
    - ./web/files:/etc/nginx/files
  links:
    - apprails
  ports:
    - "80:80"
    - "8081:8081"
apprails:
  build: ./app-rails
  command: rails s
  volumes:
    - ./app-rails/foo:/u/apps/rails
  ports:
    - "3000:3000"
